"""Change user_id to sub in all tables

Revision ID: 54cc8daa59fc
Revises: cd346a9cbec4
Create Date: 2025-08-16 13:55:08.329383

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '54cc8daa59fc'
down_revision: Union[str, Sequence[str], None] = 'cd346a9cbec4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('balance_transactions', sa.Column('sub', sa.String(), nullable=False))
    op.drop_index(op.f('ix_balance_transactions_user_id'), table_name='balance_transactions')
    op.drop_constraint(op.f('uq_transaction_idempotency'), 'balance_transactions', type_='unique')
    op.create_unique_constraint('uq_transaction_idempotency', 'balance_transactions', ['sub', 'ref', 'direction'])
    op.create_index(op.f('ix_balance_transactions_sub'), 'balance_transactions', ['sub'], unique=False)
    op.drop_column('balance_transactions', 'user_id')
    op.add_column('user_balances', sa.Column('sub', sa.String(), nullable=False))
    op.drop_index(op.f('ix_user_balances_user_id'), table_name='user_balances')
    op.create_index(op.f('ix_user_balances_sub'), 'user_balances', ['sub'], unique=True)
    op.drop_column('user_balances', 'user_id')
    op.add_column('user_plans', sa.Column('sub', sa.String(), nullable=False))
    op.drop_index(op.f('ix_user_plans_user_id'), table_name='user_plans')
    op.drop_constraint(op.f('uq_user_plan'), 'user_plans', type_='unique')
    op.create_unique_constraint('uq_user_plan', 'user_plans', ['sub', 'plan_code'])
    op.create_index(op.f('ix_user_plans_sub'), 'user_plans', ['sub'], unique=False)
    op.drop_column('user_plans', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user_plans', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_plans_sub'), table_name='user_plans')
    op.drop_constraint('uq_user_plan', 'user_plans', type_='unique')
    op.create_unique_constraint(op.f('uq_user_plan'), 'user_plans', ['user_id', 'plan_code'])
    op.create_index(op.f('ix_user_plans_user_id'), 'user_plans', ['user_id'], unique=False)
    op.drop_column('user_plans', 'sub')
    op.add_column('user_balances', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_user_balances_sub'), table_name='user_balances')
    op.create_index(op.f('ix_user_balances_user_id'), 'user_balances', ['user_id'], unique=True)
    op.drop_column('user_balances', 'sub')
    op.add_column('balance_transactions', sa.Column('user_id', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_balance_transactions_sub'), table_name='balance_transactions')
    op.drop_constraint('uq_transaction_idempotency', 'balance_transactions', type_='unique')
    op.create_unique_constraint(op.f('uq_transaction_idempotency'), 'balance_transactions', ['user_id', 'ref', 'direction'])
    op.create_index(op.f('ix_balance_transactions_user_id'), 'balance_transactions', ['user_id'], unique=False)
    op.drop_column('balance_transactions', 'sub')
    # ### end Alembic commands ###
