"""Rename tariffs table

Revision ID: 6dc6991cfb9d
Revises: 359639573958
Create Date: 2025-08-23 21:22:15.990079

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6dc6991cfb9d'
down_revision: Union[str, Sequence[str], None] = '359639573958'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariff_properties',
    sa.Column('id', sa.String(), nullable=False),
    sa.Column('plan_code', sa.String(), nullable=False),
    sa.Column('plan_property', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tariff_properties_plan_code'), 'tariff_properties', ['plan_code'], unique=False)
    op.drop_index(op.f('ix_tariffs_plan_code'), table_name='tariffs')
    op.drop_table('tariffs')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tariffs',
    sa.Column('id', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_code', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('plan_property', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('tariffs_pkey'))
    )
    op.create_index(op.f('ix_tariffs_plan_code'), 'tariffs', ['plan_code'], unique=False)
    op.drop_index(op.f('ix_tariff_properties_plan_code'), table_name='tariff_properties')
    op.drop_table('tariff_properties')
    # ### end Alembic commands ###
