"""Change user_id to sub in all tables

Revision ID: 78df72bb1dc9
Revises: e7f73b7d42f3
Create Date: 2025-08-16 14:33:06.362531

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '78df72bb1dc9'
down_revision: Union[str, Sequence[str], None] = 'e7f73b7d42f3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
