"""Change user_id to sub in all tables

Revision ID: df16f2c87dfb
Revises: 78df72bb1dc9
Create Date: 2025-08-16 14:39:59.700286

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'df16f2c87dfb'
down_revision: Union[str, Sequence[str], None] = '78df72bb1dc9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
