"""Change user_id to sub in all tables

Revision ID: e7f73b7d42f3
Revises: 54cc8daa59fc
Create Date: 2025-08-16 13:59:58.187061

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e7f73b7d42f3'
down_revision: Union[str, Sequence[str], None] = '54cc8daa59fc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
